src/memory.h
src/register.h

Prevents implicit array -> pointer decay. They can also perform bounds checking in debug mode
with `-D_GLIBCXX_DEBUG` or `-D_LIBCPP_DEBUG`
One thing I noticed with `registers.h` is that the registers aren't all zeroed out on initial construction. Is this intentional? I'd imagine this would cause some wonky initial values in some cases. I can add initializers to the members as well, if that's preferable.

Use std::array where applicable

---

src/dsp1.cpp

Prevents copying the Segment unnecessarily

 dsp1: std::move segments into the segment vector 

---

src/apbp.cpp

Provides potentially more performant setting, considering std::function is allowed to allocate
any captured values on the heap if it needs to.

apbp: std::move handlers where applicable

---

.gitignore
.travis.yml
.travis/linux-build.sh
.travis/macos-build.sh
.travis/windows-build.sh
CMakeLists.txt
appveyor.yml
src/test_verifier/CMakeLists.txt
src/test_verifier/main.cpp

In this PR, HW LLE accuracy test is included in CI checks.
Currently, due to a bug in Travis CI Windows agent, the test on that platform is disabled.
_____
And I think there will be some work to do if you want to use Catch2 Unit Test Framework. It does not provide "skip" method, and you need to sub-class the `Matcher` to make it outputs the useful information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wwylele/teakra/15)

Integrate accuracy test into CI

---

src/test_verifier/main.cpp

speed up the testing process by not calling `ToHex` so often as `ToHex` is very expensive to call.
In this PR, I added a new check type, so the `ToHex` call only happens when the target test is failed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wwylele/teakra/16)

test_verifier: speed up testing process

---

src/decoder.h

Avoids unintentionally polluting other source files with them.

decoder: Undefine instruction table macros when done with them

---

src/test_generator.cpp

This is unused, but given it's static (and non-trivial), a compiler cannot remove this instance through dead-code elimination, so this was potentially still opening another file descriptor on the system.

test_generator: Remove unused std::random_device instance in GenerateRandomState()

---

src/btdmp.h
src/teakra.cpp

Avoids potentially unnecessary reallocations that could otherwise occur when copying a std::function instance.

std::move callback functions where applicable

---

src/dma.h
src/register.h

Makes all members of the relevant structs initialize in a predictable way.

dma/register: Default initialize members where applicable

---

include/teakra/teakra.h
src/ahbm.cpp
src/ahbm.h
src/apbp.cpp
src/apbp.h
src/btdmp.h
src/dma.h
src/teakra.cpp

Fairly self-explanatory. Makes functions that don't modify member state as const.

Mark member functions const where applicable

---

src/interpreter.h

Made more than anything to bring this up.
It's very unlikely assignment here is intended, and even if this is wrong it is indeed intended, it's very non-idiomatic C++ (and matches a classic error in ternary statements, and should have a comment indicating that it's very intended).

interpreter: Correct assignment within MinMaxVtr()

---

src/test.h
src/test_generator.cpp
src/test_generator.h
src/test_generator/main.cpp

The internals of test_generator.cpp can be given internal linkage, since they aren't used outside of the translation unit.
Also, previously the test generator would potentially crash if a file handle wasn't able to be opened (since it would use a null file pointer in that case).

test_generator: Enclose internals within anonymous namespaces, also handle file I/O errors

---

src/btdmp.cpp
src/core_timing.h
src/timer.cpp

Neither of the implementers of this function modify member state, and since it's used as a getter, it can be declared a const member function.

core_timing: Make GetMaxSkip() a const member function

---

src/test_generator.cpp

I mistakenly thought fwrite reported the number of bytes written, not the number of objects.

test_generator: Amend fwrite check in GenerateTestCasesToFile()

---

src/oprand.h

It's pretty odd to leave the constructors as non-constexpr, while making any accessor functions constexpr (i.e. Index() can essentially never be used in a truly constexpr scenario, since an instance can't be constructed in a constexpr manner).

oprand: Mark Rn and Px's constructors as constexpr

---

src/bit.h

```cpp
error : variables defined in a constexpr function must be initialized
unsigned long index;
^

fix clang-cl error

---

src/interpreter.h

Fixes error C2039: 'runtime_error': is not a member of 'std'
*&lt;exception>* defines only the base `std::exceptionclass`; child classes like `std::runtime_error`, must include the *&lt;stdexcept>* header.
Further explanation can refer [here](https://stackoverflow.com/questions/25163105/stdexcept-vs-exception-headers-in-c) via stackoverflow

Use <stdexcept> header rather than <exception>

---

include/teakra/teakra.h
include/teakra/teakra_c.h
src/mod_test_generator/main.cpp
src/teakra.cpp
src/teakra_c.cpp

As talked about in `#citra-dev`, wanted for melonDS
Also fixes a compile issue in one of the tests

expose PeekRecvData for DSP_REPx peeking

---

include/teakra/teakra.h
include/teakra/teakra_c.h
src/memory_interface.cpp
src/memory_interface.h
src/teakra.cpp
src/teakra_c.cpp

More stuff melonDS needs, see [here](https://gitlab.ulyssis.org/pcy/melonDS/-/blob/d19962c4e7ea806a07f5e298fdda0e8cdb743793/src/DSi_DSP.cpp#L204-248) for example usage.

Expose program, data and mmio read/write operations, for DSP_PDATA/PADR-based DMA-style transfers

---

include/teakra/teakra.h
include/teakra/teakra_c.h
src/ahbm.cpp
src/ahbm.h
src/teakra.cpp
src/teakra_c.cpp
tests/dma.cpp

Required for melonDS, as I talked about earlier.
I've tried to make it backwards-compatible both on source and binary levels, but this has made it a bit redundant (eg. `AHBMCallback` vs `AHBMCallbackAll` etc, the former could've been replaced). If you want it to be cleaner (and break compatibility), I could do that too.

Expose AHBM things and add 16- and 32-bit memory accesses

---

CMakeLists.txt

#51 
GCC12 has made `-Werror=maybe-uninitialized` a default, it is too aggressive which leads to code error

Disable -Werror=maybe-uninitialized

---

src/mod_test_generator/main.cpp
src/step2_test_generator/main.cpp
src/test.h
src/test_generator.cpp
src/test_verifier/main.cpp

Recent versions of GCC started throwing a no-ignored-attributes warning for code using `std::unique_ptr<std::FILE, decltype(std::fclose)>`, since some attribute set on fclose gets discarded.
To fix the issue, I've added a simple fclose_deleter callable which calls fclose. It also simplifies code as it is no longer needed to pass `std::fclose` as an argument when constructing the unique_ptr. Also, according to <https://stackoverflow.com/a/76867913/10767647>, this is "better practice".

Fix build failing with -Werror=no-ignored-attributes

---

CMakeLists.txt
src/CMakeLists.txt

Hi!
In this patch set I've made some small improvements to the CMake build system: it now supports installing the project, and skipping tests by using the standard `BUILD_TESTING` option.
I'm making these changes as they are required to package Teakra in Debian; it is used by various DS/3DS emulators, and packaging this project is a prerequisite to packaging those emulators too.
I've detailed my changes in the two commit messages, but for your convenience I'll include them here.
This allows system-wide installation, useful for distribution packagers.
The minimum required CMake version is bumped to 3.14, as the `TYPE` argument of `install(DIRECTORY)` requires it. This also has the benefit of fixing the CMake 3.10 deprecation warning.
The `BUILD_TESTING` option is the standard CMake option …

Small CMake improvements

---

include/teakra/impl/register.h
include/teakra/teakra.h
src/CMakeLists.txt
src/interpreter.h
src/processor.cpp
src/processor.h
src/teakra.cpp

Continuing from #59 
There's some minor unrelated formatting changes, those are just clang-format automatically formatting based on the .clang-format in the repo though.

Processor: Expose register struct in C++ interface

---

include/teakra/disassembler_c.h

Required for my WIP Teakra Rust bindings to compile correctly, otherwise `size_t` is not properly defined

IWYU: Add stddef.h to disassembler C bindings
